# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'floraFinder' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'DeclarativeLayoutKit'
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'RxRelay'
  pod 'RxDataSources'
  pod 'FunctionalNavigationFlowKit'
  pod 'Moya/RxSwift'
  pod 'SwiftRichString'
  pod 'Kingfisher'
  
  # Pods for floraFinder

end
